# Generated by Django 6.0.3 on 2026-04-17 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['-monto', '-creado_en'], 'verbose_name': 'oferta', 'verbose_name_plural': 'ofertas'},
        ),
        migrations.AlterModelOptions(
            name='subasta',
            options={'ordering': ['-creado_en'], 'verbose_name': 'subasta', 'verbose_name_plural': 'subastas'},
        ),
        migrations.AlterField(
            model_name='oferta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='ofertante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_ofertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='subasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='subastas.subasta'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fecha_cierre',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='subastas/'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='precio_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas_vendedor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='oferta',
            constraint=models.UniqueConstraint(fields=('subasta', 'ofertante', 'monto'), name='unique_oferta_por_monto'),
        ),
    ]
