# Generated by Django 6.0.3 on 2026-06-30 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0002_alter_oferta_options_alter_subasta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='oferta',
            index=models.Index(fields=['-creado_en'], name='oferta_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subasta',
            index=models.Index(fields=['estado', '-creado_en'], name='subasta_estado_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subasta',
            index=models.Index(fields=['fecha_cierre'], name='subasta_cierre_idx'),
        ),
    ]
