# Generated by Django 6.0.3 on 2026-06-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0003_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='fecha_inicio',
        ),
    ]
