# Generated by Django 6.0.3 on 2026-07-03 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas', '0004_remove_fecha_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='ganador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subastas_ganadas', to=settings.AUTH_USER_MODEL, verbose_name='Ganador'),
        ),
    ]
